### ISSUE TITLE
Unable to use async/await in migrations

### ISSUE THREAD

**Issue by brucemontegani** [hummingbird-project/hummingbird-fluent#4]
I am trying to use the AsyncMigration but it doesn't work. I keep getting the error message:
error: protocol 'Migration' requires 'prepare(on:)' to be available in macOS 10.15.0 and newer or
error: protocol 'Migration' requires 'prepare(on:)' to be available in macOS 11.0.0 and newer

After a bunch of experimentation I got it to work by changing the swift tools version to 5.5.

Does this package need to be upgraded to use the async/await?

**Comment by adam-fowler** [comment]
Bruce I have had a look at this. The problem is you want to use async/await, your application needs to run with swift 5.5 and the macOS requirement will need to be set to v12. There is no way around this. 

The only changes this package need to support async/await is to add async versions of `HBApplication.Fluent.migrate` and `revert` which I am adding in #5 .  Everything else is provided by `fluent-kit`.
